// Code generated by "stringer -type ShutdownReason -linecomment"; DO NOT EDIT.

package component

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ShutdownReasonUninstall-0]
	_ = x[ShutdownReasonRemaining-1]
}

const _ShutdownReason_name = "卸载组件, 永久下线维护组件,暂时下线"

var _ShutdownReason_index = [...]uint8{0, 26, 51}

func (i ShutdownReason) String() string {
	if i < 0 || i >= ShutdownReason(len(_ShutdownReason_index)-1) {
		return "ShutdownReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ShutdownReason_name[_ShutdownReason_index[i]:_ShutdownReason_index[i+1]]
}
